### ISSUE TITLE
pupt-lib 1.3.0: bundled index.d.ts does not export types

### ISSUE THREAD

**Issue by apowers313** [apowers313/pupt-lib#17]
## Defect

pupt-lib 1.3.0's `dist/index.d.ts` declares all types internally but only exports `Fragment`, `jsx`, and `jsxs`. All other public types (`PuptElement`, `Component`, `RenderError`, `PostExecutionAction`, etc.) and values (`render`, `createEnvironment`, `createSearchEngine`, `isPuptElement`, `TYPE`, `PROPS`, `CHILDREN`, etc.) are inaccessible to TypeScript consumers.

The runtime exports are fine — only the type declarations are broken.

## Root Cause

In 1.2.6, `dist/index.d.ts` re-exported from individual `.d.ts` files:

```ts
export { TYPE, PROPS, CHILDREN, DEFERRED_REF } from './types/symbols';
export { isPuptElement, isDeferredRef } from './types/element';
export type { PuptNode, PuptElement, RenderError, ... } from './types';
export { render } from './render';
// ... etc
```

In 1.3.0, the declarations were bundled into a single `index.d.ts` file. The bundled file declares all types inline but ends with:

```ts
export { }
```

This empty export statement means only declarations with an inline `export declare` keyword are exported. Only three declarations have this: `Fragment`, `jsx`, and `jsxs`. Everything else (e.g. `declare const CHILDREN`, `declare interface PuptElement`, `declare type PostExecutionAction`) is declared without `export` and is therefore invisible to consumers.

## Reproduction Steps

```bash
mkdir /tmp/pupt-lib-test && cd /tmp/pupt-lib-test
npm init -y
npm install pupt-lib@1.3.0 typescript
```

Create `test.ts`:
```ts
import { render, PuptElement, createEnvironment } from "pupt-lib";
```

Run:
```bash
npx tsc --noEmit --moduleResolution bundler --module esnext test.ts
```

Result: ~3 errors per import:
```
error TS2305: Module '"pupt-lib"' has no exported member 'render'.
error TS2305: Module '"pupt-lib"' has no exported member 'createEnvironment'.
error TS2459: Module '"pupt-lib"' declares 'PuptElement' locally, but it is not exported.
```

Same imports work fine with pupt-lib@1.2.6.

## Suggested Fix

Ensure the `.d.ts` bundler adds `export` to all public declarations. For example, change:

```ts
declare const CHILDREN: unique symbol;
declare interface PuptElement<P = Record<string, unknown>> { ... }
declare function render(...): ...;
```

to:

```ts
export declare const CHILDREN: unique symbol;
export declare interface PuptElement<P = Record<string, unknown>> { ... }
export declare function render(...): ...;
```

And remove the trailing `export { }`.

Alternatively, revert to the unbundled `.d.ts` structure used in 1.2.6 which re-exported from individual declaration files.

**Comment by apowers313** [comment]
Fixed in pupt-lib 1.3.1. Verified: lint, build, and all 239 tests pass with the updated version.
